### ISSUE TITLE
Advance Attributes

### ISSUE THREAD

**Issue by GenWilhelm** [BSData/wh40k-shadow-war-armageddon#14]
Advance Attributes have been added to the GST alongside skills. Each faction needs to be updated with this so that everyone but New Recruits can take them.

 - [x] Adepta Sororitas
 - [x] Astra Militarum Veteran
 - [x] Chaos Space Marines
 - [x] Craftworlds
 - [x] Dark Eldar
 - [x] Genestealer Cults
 - [x] Grey Knights
 - [x] Harlequins
 - [x] Inquisition
 - [x] Necron
 - [x] Ork Boyz
 - [x] Skitarii
 - [x] Space Marine Scouts
 - [x] Tau Pathfinder
 - [x] Tyranid Warrior

**Comment by jksearles** [comment]
It's also worth considering putting in the point values for advances and skills. Since no fighter can start with skills, any new kill team that includes a fighter with a skill or advance would be an existing fighter and would therefor cost +15 points per advance and +25 points per skill. ("Call of the Prometheum Sprawl", SW:A Rulebook Pg. 100)
