### ISSUE TITLE
Wyches not able to take gladitorial weapons

### ISSUE THREAD

**Issue by Lynkon** [BSData/wh40k-shadow-war-armageddon#48]
All Wych kill team models should be able to take gladitorial weapons as per their special rule.

**Comment by GenWilhelm** [comment]
Which special rule is that? According to their datasheet, only Syrens and Bloodbrides may take items from the Gladiatorial Weapons list.

**Comment by Lynkon** [comment]
Under "Using a Wych Cult Kill team"

"Items of equipment from the Gladitorial Weapons list count as hand-to-hand weapons in all regards."

**Comment by GenWilhelm** [comment]
Meaning they are used in hand-to-hand combat, and interact with special rules that specify a 'hand-to-hand weapon', as you would with any other melee weapon.

They are still a separate weapons list to the regular hand-to-hand weapons, otherwise they would not be referred to as distinct lists on their datasheet. A Wych cannot take from the Gladiatorial Weapons list for the same reason a Bloodbride cannot take from the Hand-to-Hand Weapons list.
